### ISSUE TITLE
Can't catch decode error

### ISSUE THREAD

**Issue by windyrain** [pixijs/sound#141]
![image](https://user-images.githubusercontent.com/7961364/92890245-833fae00-f449-11ea-884d-495d2fc1940f.png)

decodeAudioData callback can't catch error

**Comment by windyrain** [comment]
no reply, close~

**Comment by bigtimebuddy** [comment]
Sorry didn't have time to respond or look into this yet.

**Comment by windyrain** [comment]
sentry report some error, after read pixi-sound source code, I find decodeAudioData the third param errorcallback can't catch all error.

https://github.com/pixijs/pixi-sound/blob/df4677b56c515d2bed80e34f7157784bf4b02bab/src/webaudio/WebAudioContext.ts#L337

**Comment by bigtimebuddy** [comment]
I think the problem is that some browser use promises and some older browsers use the callback handler:
https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/decodeAudioData

Because I'm using the older style callback, newer browsers might still throw an unhandledRejection if it fails. Maybe if `decodeAudioData` returns something, I should assume it's a Promise and use that instead.

**Comment by windyrain** [comment]
Thank you very match, I found my fork version modify perhaps have problem.

I direct add .catch after decodeAudioData

I will do somethine like this, Do you need a PR ?

![image](https://user-images.githubusercontent.com/7961364/93503756-1ea1b900-f94b-11ea-8579-4521801b6b74.png)

**Comment by windyrain** [comment]
by the way, lib.dom.d.ts is not exactly right.

decodeAudioData(audioData: ArrayBuffer, successCallback?: DecodeSuccessCallback | null, errorCallback?: DecodeErrorCallback | null): Promise<AudioBuffer>;

typeof return value should be void | Promise<AudioBuffer>

**Comment by bigtimebuddy** [comment]
Yes, could you make a PR? Also, I don't think you need `result instanceof Promise`. Otherwise :+1:

**Comment by windyrain** [comment]
This is my PR: https://github.com/pixijs/pixi-sound/pull/143
