### ISSUE TITLE
Usage question in playing a same sound with different filters

### ISSUE THREAD

**Issue by yueyuzhao** [pixijs/sound#185]
Hi, let's consider such a case:

On a scene, there are two birds, one is on the left, the other one is on the right, they can both make the sound `bird.mp3`, the left bird should have `StereoFilter` with `pan = -1` and the right bird should have `StereoFilter` with `pan = 1`. Here is the demo codes:

```js
function cloneSound(snd) {
    return PIXI.sound.Sound.from({
        url: snd.url,
        source: snd.source,
    })
}

const sound = PIXI.sound.Sound.from('resources/bird.mp3');
const leftBirdSound = cloneSound(sound);
const rightBirdSound = cloneSound(sound);

leftBirdSound.filters = [
    new PIXI.sound.filters.StereoFilter(-1),
];
rightBirdSound.filters = [
    new PIXI.sound.filters.StereoFilter(1),
];

leftBirdSound.play();
setTimeout(function () {
    rightBirdSound.play();
}, 50);
```

But I don't think this is the ideal way. Or we can add a `pan` parameter to `PlayOptions` for this case or we can add filters to `WebAudioInstance`?

**Comment by bigtimebuddy** [comment]
I think adding filters to instances could work and someone else requested this feature.

The reason I didn't add a stereo pan to the play options, sound or instance was because panning isn't supported in the HTML Audio fallback. Also, there are other approaches for panning not just stereo (like 3D spacial panning). A filter seemed like the the best option, but I agree it's a little clumsy. 

Maybe we can add a play option, use a filter, and hide the implementation filter details.

**Comment by yueyuzhao** [comment]
Oh, thank you for the reply. I will look into the ways that add `filters` option to play options.
