### ISSUE TITLE
Questions about filters and fading

### ISSUE THREAD

**Issue by ntkcreative** [pixijs/sound#54]
I would like to ask about 2 things:

1. Is there a way to play the same sound with different filters at the same time?
e.g. Panning effect left-to-right for 5 sounds played 100 ms after each other.

2. From what I understand, the library supported fadeIn/fadeOut features. Were they removed?

Thank you.

**Comment by bigtimebuddy** [comment]
1. Currently, filters can only be assigned on a per-sound, not per-instance, basis. I had not consider this use-case, but might be worth adding! As a workaround, you could load separate, but identical sound files and apply filters. Less than ideal, but adding filters to instances might take some time to figure out the best approach.

2. Yes, the `fadeIn` and `fadeOut` options were removed, mostly because they were half-baked and not wanting to add internal tweening. I would suggest that you use a lerp function to tween the `volume` property of a sound or instance.

**Comment by ntkcreative** [comment]
It would be great if the filters were to be used not only for the sounds but also for instances. In the meantime we will use the proposed solution.

Thanks.
